### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:30:35.056061000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:30:38.872266000 -07:00
:result: :ok
:message: 'Merge Success: 1864858906b19143ce84583c65116ad58a214df5 onto target branch:
  master'
:output: |-
  Updating 23b73c0..1864858
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:30:38.872324000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:30:38.881242000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_182 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:30:38.881378000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:30:38.889233000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_182 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#182 (1864858906b19143ce84583c65116ad58a214df5 on to master)

``` ---
:sha: 32a113876aded596fd5303ea3c174d2c5cf8ba60
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
