### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:

Code reviews from: @davidpuddy1, @bobsmith1.
Merging and closing this PR.
Build Status:

#### _MERGE_

`````` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 14:57:00.127533000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 14:57:02.417591000 -07:00
:result: :ok
:message: Merge Success


#### *BUILD*
```yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 14:57:02.417643000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 14:57:02.426369000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_130 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_130 && make build
- |
  BUILD OK
- 0


#### *TEST*
```yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 14:57:02.426542000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 14:57:02.434799000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_130 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_130 && make test
- |
  TEST OK
- 0


``````

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#130 (31260b1e4579f16c80fa02e88c5bc588aa0242b6 on to master)
 `{:sha=>"bfe5b91cdc9fc2913c8f4671b7b3c7677b868063", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
