### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/346:

> :+1: Looks good! :+1:

### MERGE   OK

> Started at: 2016-08-08 18:05
> Duration: 3 seconds.

```


Updating c69effe..44ea7d2
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 18:05
> Duration: 0 seconds.

Exit Code: 0

```
cd /tmp/thumbs/BashoOps_prtester_346 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 18:05
> Duration: 0 seconds.

Exit Code: 0

```
cd /tmp/thumbs/BashoOps_prtester_346 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/346_ (_44ea7d25a2b1bfdb99c83b83aafafa07bf439d4c_ on to _master_)

``` yaml
---
:sha: a25134e2e93effd515d19e5860e17af3fa926f01
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
