### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
Code reviews from: @davidpuddy1@bobsmith1
Merging and closing this PR.
Build Status:

#### _MERGE_

|started_at|:||

|2016-08-06T14:40:33-07:00|:||

|ended_at|:||

|2016-08-06T14:40:36-07:00|:||

|result|:||

|ok|:||

|message|:||

|Merge Success|:||

#### _BUILD_

|started_at|:||

|2016-08-06T14:40:36-07:00|:||

|ended_at|:||

|2016-08-06T14:40:36-07:00|:||

|result|:||

|ok|:||

|command|:||

|cd /tmp/thumbs/BashoOps_prtester_103 && make build|:||

|output|:||

|BUILD OK
|:||

|exit_code|:||

|0|:||

|message|:||

|OK|:|cd /tmp/thumbs/BashoOps_prtester_103 && make build|

#### _TEST_

|started_at|:||

|2016-08-06T14:40:36-07:00|:||

|ended_at|:||

|2016-08-06T14:40:36-07:00|:||

|result|:||

|ok|:||

|command|:||

|cd /tmp/thumbs/BashoOps_prtester_103 && make test|:||

|output|:||

|TEST OK
|:||

|exit_code|:||

|0|:||

|message|:||

|OK|:|cd /tmp/thumbs/BashoOps_prtester_103 && make test|

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#103 (6f0259ed75d8eb031d5a729d70e1b7e958e05e3f on to master) #Sawyer::Resource:0x007fb9ecaafb88

**Pull request merged**
