### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by davidx** [comment]
Looks good! :+1:
Code reviews from: @davidpuddy1,@bobsmith1.
Merging and closing this PR.
Build Status:

#### merge

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:45:53.736657000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:45:55.475964000 -07:00
:result: :ok
:message: Merge Success

```

#### build

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:45:55.476011000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:45:55.484541000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_1 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_1 && make build
- |
  BUILD OK
- 0

```

#### test

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:45:55.484648000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:45:55.493822000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_1 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_1 && make test
- |
  TEST OK
- 0

```

**Comment by davidx** [comment]
Merge successfull!

**Pull request merged**
