### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/327: :+1: Looks good! :+1:

| _MERGE_ |  |  |
| --- | --- | --- |
|  | Started at |  |
|  | Ended at | 2016-08-08T17:24:33-07:00 |
|  | Command |  |
|  | Exit Code |  |
|  | Output |  |
|  |  |  |

|---|---|---|
|   |   |  |
| |  |
| | Started at | 2016-08-08T17:24:28-07:00 |
| | Started at | 2016-08-08T17:24:28-07:00 |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | `shell` |

| _BUILD_ |  |  |
| --- | --- | --- |
|  | Started at |  |
|  | Ended at | 2016-08-08T17:24:33-07:00 |
|  | Command |  |
|  | Exit Code |  |
|  | Output |  |
|  |  |  |

|---|---|---|
|   |   |  |
| |  |
| | Started at | 2016-08-08T17:24:33-07:00 |
| | Started at | 2016-08-08T17:24:33-07:00 |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | `shell` |

| _TEST_ |  |  |
| --- | --- | --- |
|  | Started at |  |
|  | Ended at | 2016-08-08T17:24:33-07:00 |
|  | Command |  |
|  | Exit Code |  |
|  | Output |  |
|  |  |  |

|---|---|---|
|   |   |  |
| |  |
| | Started at | 2016-08-08T17:24:33-07:00 |
| | Started at | 2016-08-08T17:24:33-07:00 |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | `shell` |

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/327_ (_4d8d9974a67cb56206fd2da71bd41b93d011d082_ on to _master_)

``` yaml
---
:sha: 0f9a3a5277bb11e9572020499ae709e4a5bbcb4d
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
