### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
Code reviews from: .
@davidpuddy1
.
@bobsmith1

Merging and closing this PR.
Build Status:

#### MERGE

|| started_at|:|||

|| 2016-08-06T14:32:59-07:00|:|||

|| ended_at|:|||

|| 2016-08-06T14:33:02-07:00|:|||

|| result|:|||

|| ok|:|||

|| message|:|||

|| Merge Success|:|||

#### BUILD

|| started_at|:|||

|| 2016-08-06T14:33:02-07:00|:|||

|| ended_at|:|||

|| 2016-08-06T14:33:02-07:00|:|||

|| result|:|||

|| ok|:|||

|| command|:|||

|| cd /tmp/thumbs/BashoOps_prtester_90 && make build|:|||

|| output|:|||

|| BUILD OK
|:|||

|| exit_code|:|||

|| 0|:|||

|| message|:|||

|| OK|:|cd /tmp/thumbs/BashoOps_prtester_90 && make build||

#### TEST

|| started_at|:|||

|| 2016-08-06T14:33:02-07:00|:|||

|| ended_at|:|||

|| 2016-08-06T14:33:02-07:00|:|||

|| result|:|||

|| ok|:|||

|| command|:|||

|| cd /tmp/thumbs/BashoOps_prtester_90 && make test|:|||

|| output|:|||

|| TEST OK
|:|||

|| exit_code|:|||

|| 0|:|||

|| message|:|||

|| OK|:|cd /tmp/thumbs/BashoOps_prtester_90 && make test||

**Comment by BashoOps** [comment]
Merge successfull!

**Pull request merged**
