### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/353:

> :+1: Looks good! :+1:

### MERGE   OK

> Started at: 2016-08-08 18:20
> Duration: 3 seconds.
> Result:  OK
> Exit Code:  OK

```



Updating 338f031..1829687
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 18:20
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_353 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 18:20
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_353 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/353_ (_1829687d884a307b835c0b811abc0efe5c09fc3d_ on to _master_)

``` yaml
---
:sha: 044855c4068c9e01393aa8eabee48e2aa2bd53a8
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
