### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/334: :+1: Looks good! :+1:

### MERGE\*   _OK_

|---|---|---|
|   |  Started at | 2016-08-08T17:37:44-07:00 |
|   |  Ended at | 2016-08-08T17:37:48-07:00 |

|   |  Output | `Updating 36d5180..6090406
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)` |
|   |   |   |

### BUILD\*   _OK_

|---|---|---|
|   |  Started at | 2016-08-08T17:37:48-07:00 |
|   |  Ended at | 2016-08-08T17:37:48-07:00 |

|   |  Command | cd /tmp/thumbs/BashoOps_prtester_334 && make build |

|   |  Exit Code | 0 |

|   |  Output | `BUILD OK
` |
|   |   |   |

### TEST\*   _OK_

|---|---|---|
|   |  Started at | 2016-08-08T17:37:48-07:00 |
|   |  Ended at | 2016-08-08T17:37:48-07:00 |

|   |  Command | cd /tmp/thumbs/BashoOps_prtester_334 && make test |

|   |  Exit Code | 0 |

|   |  Output | `TEST OK
` |
|   |   |   |

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/334_ (_609040654e54dbd3c7c104d18386c87e63966e3a_ on to _master_)

``` yaml
---
:sha: d234f480703552f8018ade58969dbf98269b4e45
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
