### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/312: :+1: Looks good! :+1:

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:54:20.001256000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:54:22.498082000 -07:00
:result: :ok
:message: 'Merge Success: 487abd97d9ecb5b796cba365d71f7092ccce0dd9 onto target branch:
  master'
:output: |-
  Updating cee21d9..487abd9
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:54:22.498147000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:54:22.506852000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_312 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:54:22.507007000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:54:22.515654000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_312 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/312_ (_487abd97d9ecb5b796cba365d71f7092ccce0dd9_ on to _master_)

``` yaml
---
:sha: db0843c903c088a2fbc7c856611aeea832166f59
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
