### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:

Code reviews from: @davidpuddy1, @bobsmith1
Merging and closing this PR.
Build Status:

#### _MERGE_

|started_at|:||
|2016-08-06T14:46:16-07:00|:||
|ended_at|:||
|2016-08-06T14:46:19-07:00|:||

|result|:||

|ok|:||

|message|:||
|Merge Success|:||

#### _BUILD_

|started_at|:||

|2016-08-06T14:46:19-07:00|:||

|ended_at|:||

|2016-08-06T14:46:19-07:00|:||

|result|:||

|ok|:||

|command|:||

|cd /tmp/thumbs/BashoOps_prtester_111 && make build|:||

|output|:||

|BUILD OK
|:||

|exit_code|:||

|0|:||

|message|:||

|OK|:|cd /tmp/thumbs/BashoOps_prtester_111 && make build|

#### _TEST_

|started_at|:||

|2016-08-06T14:46:19-07:00|:||

|ended_at|:||

|2016-08-06T14:46:19-07:00|:||

|result|:||

|ok|:||

|command|:||

|cd /tmp/thumbs/BashoOps_prtester_111 && make test|:||

|output|:||

|TEST OK
|:||

|exit_code|:||

|0|:||

|message|:||

|OK|:|cd /tmp/thumbs/BashoOps_prtester_111 && make test|

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#111 (ebd866a74c80bd86013e93388e8795b9d2778af4 on to master)
 `{:sha=>"d864a10fb0d990a0f7675c94b991da7c25bbffee", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
