### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/410_ (_dc2515b1a0aace23c6b4693e776c5681c8068eac_ on to _master_)

``` yaml
---
:sha: 1a55db1e4a08c8bf85faba5668121c21b7a61ab7
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
