### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/412:

Looks good! @BashoOps  :+1:

### MERGE   OK

> Started at: 2016-08-08 18:53
> Duration: 3 seconds.
> Result:  OK
> Exit Code:  OK

```



Updating 1a55db1..6f2276f
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 18:53
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_412 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 18:53
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_412 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Code reviews from: _@davidpuddy1_, _@bobsmith1_.

##### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/412_ (_6f2276f6812e3d3e80b57df2a45fe85c6ea363e6_ on to _master_)

``` yaml
---
:sha: de1a1a439145f2594751292265989dce9f0ed72b
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
