### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/418_ (_6cb8e27174968aed44ba22e389e21a8e1bac14e5_ on to _master_)

``` yaml
---
:sha: 865d1ed04acd3654e3bb12dc41b0c73618076669
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
