### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:59:10.084982000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:59:12.905088000 -07:00
:result: :ok
:message: 'Merge Success: 3617bc56b05cfcbf8793f90fe7332ba7ab8f0650 onto target branch:
  master'
:output: |-
  Updating a5e2d9e..3617bc5
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:59:12.905141000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:59:12.913737000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_221 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:59:12.913892000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:59:12.922211000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_221 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Pull request closed without merging**
