### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:11:20.635465000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:11:24.033310000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:11:24.033352000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:11:24.041154000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_160 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_160 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:11:24.041261000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:11:24.048862000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_160 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_160 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#160 (a7ba379f251ed3c4a20b08982ad07f52187269b2 on to master)

``` ---
:sha: 7461e5d1827cc9072a545a9394470394b68ee023
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
