### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:06:57.578621000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:07:00.153885000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:07:00.153938000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:07:00.162490000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_153 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_153 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:07:00.162637000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:07:00.170309000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_153 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_153 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#153 (12111cd869874b309c4cbcd75de8f3cb42f93500 on to master)

  ``` --- -1922349252397329958
...

```
```

**Pull request merged**
