### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/234: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:06:35.983468000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:06:38.616652000 -07:00
:result: :ok
:message: 'Merge Success: 4276982a4b0535905b4a3404ec8f04abeecef88c onto target branch:
  master'
:output: |-
  Updating 9cbf651..4276982
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:06:38.616706000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:06:38.624961000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_234 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:06:38.625095000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:06:38.633164000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_234 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/234_ (_4276982a4b0535905b4a3404ec8f04abeecef88c_ on to _master_)

``` yaml
---
:sha: a6bc5643a73308f65c8ccd8b9f1d5f276db26c63
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
