### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/321: :+1: Looks good! :+1:

`````` markdown
| *MERGE*  |   |
| | Started at |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | ```shell ``` |
``````

`````` markdown
| *BUILD*  |   |
| | Started at |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | ```shell ``` |
``````

`````` markdown
| *TEST*  |   |
| | Started at |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | ```shell ``` |
``````

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/321_ (_fdbc47165603ac71e0f890cf76559a00987d1532_ on to _master_)

``` yaml
---
:sha: 075f49c1a4a734b0843ba58e6d54b85966008c8f
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
