### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/329: :+1: Looks good! :+1:

| _MERGE_ |  |  |
| --- | --- | --- |
|  | Started at |  |
|  | Ended at | 2016-08-08T17:26:35-07:00 |
|  | Command |  |
|  | Exit Code |  |
|  | Output | Updating 0f9a3a5..75b6e9e |

Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-) |
|   |   |   |

| _BUILD_ |  |  |
| --- | --- | --- |
|  | Started at |  |
|  | Ended at | 2016-08-08T17:26:35-07:00 |
|  | Command | cd /tmp/thumbs/BashoOps_prtester_329 && make build |
|  | Exit Code | 0 |
|  | Output | BUILD OK |
|  |  |  |
|  |  |  |

| _TEST_ |  |  |
| --- | --- | --- |
|  | Started at |  |
|  | Ended at | 2016-08-08T17:26:35-07:00 |
|  | Command | cd /tmp/thumbs/BashoOps_prtester_329 && make test |
|  | Exit Code | 0 |
|  | Output | TEST OK |
|  |  |  |
|  |  |  |

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/329_ (_75b6e9e73f0e33e5222c8b3030427960e7db7ffb_ on to _master_)

``` yaml
---
:sha: 848d80aad60bd4cda01428a1f16d0d3fa60c1ee6
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
