### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:11:28.703055000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:11:30.637887000 -07:00
:result: :ok
:message: 'Merge Success: 69a5482e56fd0ed76b4fc4c46540c57b256e50fe onto target branch:
  master'
:output: |-
  Updating 37ac588..69a5482
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:11:30.637929000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:11:30.645603000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_194 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:11:30.645695000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:11:30.653448000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_194 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#194 (69a5482e56fd0ed76b4fc4c46540c57b256e50fe on to master)

``` yaml
---
:sha: 454d30f247ff3ad64d91eedcc9505a7903fa90ed
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
