### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:09:23.930526000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:09:26.145975000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:09:26.146030000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:09:26.154993000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_158 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_158 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:09:26.155167000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:09:26.163363000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_158 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_158 && make test
- |
  TEST OK
- 0

```

**Pull request merged**
