### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:42:58.060229000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:43:00.664328000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:43:00.664398000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:43:00.672464000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:43:00.672624000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:43:00.680821000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:43:50.307871000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:43:59.469751000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:43:59.469786000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:43:59.479296000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:43:59.479417000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:43:59.488016000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:44:14.492078000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:44:26.678245000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:44:26.678290000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:44:26.695453000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:44:26.695508000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:44:26.704571000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:44:37.272583000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:44:53.989875000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:44:53.989975000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:44:53.998669000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:44:53.998799000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:44:54.007187000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:45:10.542523000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:45:25.871740000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:45:25.871797000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:45:25.880536000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:45:25.880653000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:45:25.888857000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:45:37.872843000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:45:52.486807000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:45:52.486868000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:45:52.495749000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:45:52.495851000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:45:52.505025000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:46:15.134255000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:46:25.345977000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:46:25.346053000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:46:25.367896000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:46:25.367971000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:46:25.378741000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:46:36.492706000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:46:53.182782000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:46:53.182846000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:46:53.190898000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:46:53.191021000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:46:53.199147000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:47:04.701102000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:47:22.327836000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:47:22.327914000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:47:22.336753000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:47:22.336962000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:47:22.345420000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:47:32.584324000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:47:54.562164000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:47:54.562214000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:47:54.571510000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:47:54.571651000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:47:54.579933000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:48:16.059830000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:48:25.213129000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:48:25.213156000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:48:25.223378000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:48:25.223521000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:48:25.236436000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:48:40.357128000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:48:52.391106000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:48:52.391157000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:48:52.411001000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:48:52.411056000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:48:52.420332000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:49:07.191497000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:49:22.436824000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:49:22.436877000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:49:22.444930000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:49:22.445034000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:49:22.458525000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:49:34.959304000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:49:50.628256000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:49:50.628317000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:49:50.642768000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:49:50.642912000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:49:50.652528000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:50:02.380382000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:50:24.442495000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:50:24.442548000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:50:24.450558000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:50:24.450716000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:50:24.458642000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:50:35.567773000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:50:51.986806000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:50:51.986866000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:50:51.999894000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:50:52.000042000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:50:52.009475000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/308: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:51:02.960249000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:51:18.501649000 -07:00
:result: :ok
:message: 'Merge Success: 62d94ecdc7d5fb93cd0f1c8f7f7d9ea19c1eaeaf onto target branch:
  master'
:output: |-
  Updating cee21d9..62d94ec
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:51:18.501703000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:51:18.509148000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:51:18.509269000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:51:18.517335000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_308 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Pull request closed without merging**
