### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:12:49.320365000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:12:57.777056000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:12:57.777106000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:12:57.785315000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:12:57.785458000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:12:57.793632000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:13:28.997441000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:13:40.815665000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:13:40.815736000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:13:40.824800000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:13:40.824945000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:13:40.833379000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:13:57.267267000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:14:03.901614000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:14:03.901651000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:14:03.918159000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:14:03.918290000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:14:03.927252000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:14:15.531158000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:14:25.101054000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:14:25.101113000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:14:25.110123000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:14:25.110492000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:14:25.118889000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:14:38.207805000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:14:45.229034000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:14:45.229080000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:14:45.244919000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:14:45.245174000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:14:45.255207000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:14:58.450100000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:15:11.624546000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:15:11.624595000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:15:11.643872000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:15:11.643960000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:15:11.653516000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:15:23.167543000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:15:32.589850000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:15:32.589915000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:15:32.599002000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:15:32.599136000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:15:32.607214000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:15:43.209526000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:15:52.630626000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:15:52.630701000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:15:52.639413000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:15:52.639569000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:15:52.648223000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:16:13.416673000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:16:20.233612000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:16:20.233671000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:16:20.250253000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:16:20.250328000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:16:20.259910000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:16:35.502211000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:16:41.532800000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:16:41.532849000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:16:41.551379000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:16:41.551461000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:16:41.562204000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:17:07.129022000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:17:16.491295000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:17:16.491355000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:17:16.501183000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:17:16.501336000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:17:16.510125000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:17:29.875409000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:17:36.722693000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:17:36.722745000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:17:36.740136000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:17:36.740209000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:17:36.750266000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:17:49.818453000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:17:56.582648000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:17:56.582741000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:17:56.600522000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:17:56.600588000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:17:56.612515000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:18:08.518364000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:18:18.139781000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:18:18.139843000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:18:18.148463000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:18:18.148597000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:18:18.156623000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:18:30.679329000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:18:40.615286000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:18:40.615347000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:18:40.624421000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:18:40.624559000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:18:40.633788000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:18:52.481794000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:19:01.800187000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:19:01.800245000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:19:01.808692000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:19:01.808840000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:19:01.817117000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:19:15.292955000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:19:21.999487000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:19:21.999526000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:19:22.014578000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:19:22.014658000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:19:22.024774000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:19:32.721537000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:19:42.403969000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:19:42.404023000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:19:42.412897000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:19:42.413022000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:19:42.421338000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:20:00.214825000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:20:20.732702000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:20:20.733338000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:20:20.750531000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:20:20.750605000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:20:20.760410000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:20:31.643649000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:20:48.018900000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:20:48.018945000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:20:48.027413000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:20:48.027541000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:20:48.036241000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:21:02.681379000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:21:17.405894000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:21:17.405940000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:21:17.422529000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:21:17.422601000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:21:17.432361000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/306: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:21:32.803367000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:21:45.712558000 -07:00
:result: :ok
:message: 'Merge Success: c5da6adb1bf96497723f2b495b7523d1d1d1e103 onto target branch:
  master'
:output: |-
  Updating cee21d9..c5da6ad
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:21:45.712609000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:21:45.731581000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:21:45.731969000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:21:45.740082000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_306 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Pull request closed without merging**
