### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:29:33.650034000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:29:36.015026000 -07:00
:result: :ok
:message: 'Merge Success: 8557ad680759b1e8c33b1578ef9a31f6036be2b4 onto target branch:
  master'
:output: |-
  Updating fc9586f..8557ad6
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:29:36.015089000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:29:36.023741000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_179 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:29:36.023864000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:29:36.032093000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_179 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#179 (8557ad680759b1e8c33b1578ef9a31f6036be2b4 on to master)

``` ---
:sha: 23b73c078ac3a8a96708d5b257547e9582d703ff
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
