### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/331: :+1: Looks good! :+1:

| _MERGE_ | _OK_ |  |
| --- | --- | --- |
|  | Started at | 2016-08-08T17:29:37-07:00 |
|  | Ended at | 2016-08-08T17:29:40-07:00 |
|  | Command |  |
|  | Exit Code |  |
|  | Output | ``` Updating eb41e3f..973f065 |

Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)``` |  |
|   |   |   |  |

| _BUILD_ | _OK_ |  |
| --- | --- | --- |
|  | Started at | 2016-08-08T17:29:40-07:00 |
|  | Ended at | 2016-08-08T17:29:40-07:00 |
|  | Command | cd /tmp/thumbs/BashoOps_prtester_331 && make build |
|  | Exit Code | 0 |
|  | Output | ``` BUILD OK |
| ``` |  |  |
|  |  |  |

| _TEST_ | _OK_ |  |
| --- | --- | --- |
|  | Started at | 2016-08-08T17:29:40-07:00 |
|  | Ended at | 2016-08-08T17:29:40-07:00 |
|  | Command | cd /tmp/thumbs/BashoOps_prtester_331 && make test |
|  | Exit Code | 0 |
|  | Output | ``` TEST OK |
| ``` |  |  |
|  |  |  |

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/331_ (_973f0659f3b7ae6df30123012348d38358ae3568_ on to _master_)

``` yaml
---
:sha: 57b15bbbf78393c14c31a2ca5c09ab5329bd21ca
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
