### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:

Code reviews from: @davidpuddy1, @bobsmith1.
Merging and closing this PR.
Build Status:

#### _MERGE_

``` yaml
---
- :started_at
- !ruby/object:DateTime 2016-08-06 14:52:31.737478000 -07:00

```

  #   

``` yaml
---
- :ended_at
- !ruby/object:DateTime 2016-08-06 14:52:34.371659000 -07:00

```

  #   

``` yaml
---
- :result
- :ok

```

  #   

``` yaml
---
- :message
- Merge Success

```

  #   

#### _BUILD_

``` yaml
---
- :started_at
- !ruby/object:DateTime 2016-08-06 14:52:34.371701000 -07:00

```

  #   

``` yaml
---
- :ended_at
- !ruby/object:DateTime 2016-08-06 14:52:34.379954000 -07:00

```

  #   

``` yaml
---
- :result
- :ok

```

  #   

``` yaml
---
- :command
- cd /tmp/thumbs/BashoOps_prtester_123 && make build

```

  #   

``` yaml
---
- :output
- |
  BUILD OK

```

  #   

``` yaml
---
- :exit_code
- 0

```

  #   

``` yaml
---
- :message
- - OK
  - cd /tmp/thumbs/BashoOps_prtester_123 && make build
  - |
    BUILD OK
  - 0

```

  #   

#### _TEST_

``` yaml
---
- :started_at
- !ruby/object:DateTime 2016-08-06 14:52:34.380111000 -07:00

```

  #   

``` yaml
---
- :ended_at
- !ruby/object:DateTime 2016-08-06 14:52:34.388510000 -07:00

```

  #   

``` yaml
---
- :result
- :ok

```

  #   

``` yaml
---
- :command
- cd /tmp/thumbs/BashoOps_prtester_123 && make test

```

  #   

``` yaml
---
- :output
- |
  TEST OK

```

  #   

``` yaml
---
- :exit_code
- 0

```

  #   

``` yaml
---
- :message
- - OK
  - cd /tmp/thumbs/BashoOps_prtester_123 && make test
  - |
    TEST OK
  - 0

```

  #

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#123 (203b443235e31e94c4cb2d69778bd7888307d8e4 on to master)
 `{:sha=>"36526eaa15cb8cb57b8e922e0a42fb44b54be59b", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
