### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/420:

Looks good @BashoOps!  :+1:

### MERGE   OK

> Started at: 2016-08-08 19:47
> Duration: 3 seconds.
> Result:  OK
> Message: Merge Success: 085894c1567663c52d038eadc041713dd14c44ef onto target branch: master
> Exit Code:  OK

```



Updating 865d1ed..085894c
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 19:47
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_420 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 19:47
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_420 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Code reviews from: _@davidpuddy1_, _@bobsmith1_.

##### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/420_ (_085894c1567663c52d038eadc041713dd14c44ef_ on to _master_)

``` yaml
---
:sha: 4a78fd3e1997f14cb456901d5d1856bae763a578
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
