### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:12:24.948544000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:12:26.907389000 -07:00
:result: :ok
:message: 'Merge Success: b81ea2cbbb894ba9621ea400a27a8b7792eb2dc0 onto target branch:
  master'
:output: |-
  Updating 454d30f..b81ea2c
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:12:26.907456000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:12:26.916113000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_197 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:12:26.916257000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:12:26.924140000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_197 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#197 (b81ea2cbbb894ba9621ea400a27a8b7792eb2dc0 on to master)

``` yaml
---
:sha: 155891d9a9942d56d29e629561b4e45d8df0b949
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
