### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/395_ (_c14aee1bdaf7a2f0bcc37881d09c2fb64603175d_ on to _master_)

``` yaml
---
:sha: d6f084f565056dadd33058eaa6f1cc03fd374030
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
