### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:52:06.501828000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:52:10.412441000 -07:00
:result: :ok
:message: 'Merge Success: 01486307ea1476b8e81507f4c78b4aa0be5c8341 onto target branch:
  master'
:output: |-
  Updating cb426d9..0148630
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:52:10.412499000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:52:10.421168000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_214 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:52:10.425247000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:52:10.433998000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_214 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#214 (01486307ea1476b8e81507f4c78b4aa0be5c8341 on to master)

``` yaml
---
:sha: d76b8208084eda094f1a57f87fe49666363e64d1
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
