### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/311: :+1: Looks good! :+1:

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:51:47.835957000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:51:50.553776000 -07:00
:result: :ok
:message: 'Merge Success: 0d8da1ba85ef67b6edae4fab1145c9c8c8323ada onto target branch:
  master'
:output: |-
  Updating cee21d9..0d8da1b
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:51:50.553842000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:51:50.562300000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_311 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:51:50.562445000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:51:50.570466000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_311 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Pull request closed without merging**
