### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:55:13.543252000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:55:17.137423000 -07:00
:result: :ok
:message: 'Merge Success: d8aa288f5eaa18ff53094cee848ae774a92a21e4 onto target branch:
  master'
:output: |-
  Updating fe2adf3..d8aa288
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:55:17.137479000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:55:17.146310000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_219 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:55:17.146475000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:55:17.155002000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_219 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#219 (d8aa288f5eaa18ff53094cee848ae774a92a21e4 on to master)

``` yaml
---
:sha: a5e2d9e1db439e8b59a07716666b7022de25fb41
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
