### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/330: :+1: Looks good! :+1:

| _MERGE_ | _OK_ |  |
| --- | --- | --- |
|  | Started at | 2016-08-08T17:28:51-07:00 |
|  | Ended at | 2016-08-08T17:28:54-07:00 |
|  | Command |  |
|  | Exit Code |  |
|  | Output | Updating 848d80a..4d36ac6 |

Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-) |  |
|   |   |   |  |

| _BUILD_ | _OK_ |  |
| --- | --- | --- |
|  | Started at | 2016-08-08T17:28:54-07:00 |
|  | Ended at | 2016-08-08T17:28:54-07:00 |
|  | Command | cd /tmp/thumbs/BashoOps_prtester_330 && make build |
|  | Exit Code | 0 |
|  | Output | BUILD OK |
|  |  |  |
|  |  |  |

| _TEST_ | _OK_ |  |
| --- | --- | --- |
|  | Started at | 2016-08-08T17:28:54-07:00 |
|  | Ended at | 2016-08-08T17:28:54-07:00 |
|  | Command | cd /tmp/thumbs/BashoOps_prtester_330 && make test |
|  | Exit Code | 0 |
|  | Output | TEST OK |
|  |  |  |
|  |  |  |

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/330_ (_4d36ac6af86418aea3336873e2639c6177513cad_ on to _master_)

``` yaml
---
:sha: eb41e3feba10bf97e751fb50d7b985151d4cb57e
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
