### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:

Code reviews from: @davidpuddy1, @bobsmith1.
Merging and closing this PR.
Build Status:

#### _MERGE_

``` yaml
---
- :merge
- :started_at: !ruby/object:DateTime 2016-08-06 14:54:20.622426000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:54:23.211386000 -07:00
  :result: :ok
  :message: Merge Success

```

  #   

``` yaml
---
- :build
- :started_at: !ruby/object:DateTime 2016-08-06 14:54:23.211425000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:54:23.220157000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_125 && make build
  :output: |
    BUILD OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_125 && make build
  - |
    BUILD OK
  - 0

```

  #   

``` yaml
---
- :test
- :started_at: !ruby/object:DateTime 2016-08-06 14:54:23.220303000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:54:23.228996000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_125 && make test
  :output: |
    TEST OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_125 && make test
  - |
    TEST OK
  - 0

```

  #   

#### _BUILD_

``` yaml
---
- :merge
- :started_at: !ruby/object:DateTime 2016-08-06 14:54:20.622426000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:54:23.211386000 -07:00
  :result: :ok
  :message: Merge Success

```

  #   

``` yaml
---
- :build
- :started_at: !ruby/object:DateTime 2016-08-06 14:54:23.211425000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:54:23.220157000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_125 && make build
  :output: |
    BUILD OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_125 && make build
  - |
    BUILD OK
  - 0

```

  #   

``` yaml
---
- :test
- :started_at: !ruby/object:DateTime 2016-08-06 14:54:23.220303000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:54:23.228996000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_125 && make test
  :output: |
    TEST OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_125 && make test
  - |
    TEST OK
  - 0

```

  #   

#### _TEST_

``` yaml
---
- :merge
- :started_at: !ruby/object:DateTime 2016-08-06 14:54:20.622426000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:54:23.211386000 -07:00
  :result: :ok
  :message: Merge Success

```

  #   

``` yaml
---
- :build
- :started_at: !ruby/object:DateTime 2016-08-06 14:54:23.211425000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:54:23.220157000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_125 && make build
  :output: |
    BUILD OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_125 && make build
  - |
    BUILD OK
  - 0

```

  #   

``` yaml
---
- :test
- :started_at: !ruby/object:DateTime 2016-08-06 14:54:23.220303000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:54:23.228996000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_125 && make test
  :output: |
    TEST OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_125 && make test
  - |
    TEST OK
  - 0

```

  #

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#125 (ee034bf7211828fe83a5d0b40270fb0c989d9a6e on to master)
 `{:sha=>"52984ce31d86416cba74ee0a1ddf570ee6959b32", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
