### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/423_ (_6faae9a5f6af64ffa9d3a0be7dc2ee51513ca178_ on to _master_)

``` yaml
---
:sha: c8b7a764f5e321a3a082bbd0462f4a57629e548e
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
