### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:54:08.362856000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:54:10.774463000 -07:00
:result: :ok
:message: 'Merge Success: 7661b6f9f374acd305546d956f6be9f235909ba3 onto target branch:
  master'
:output: |-
  Updating d76b820..7661b6f
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:54:10.774515000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:54:10.783043000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_216 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:54:10.783171000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:54:10.791263000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_216 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#216 (7661b6f9f374acd305546d956f6be9f235909ba3 on to master)

``` yaml
---
:sha: fe2adf35d034cbd8e9b8ee59cf0ece4cad5a88fe
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
