### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:

Code reviews from: 
Merging and closing this PR.
Build Status:

#### _MERGE_

|started_at|:||

|2016-08-06T14:44:00-07:00|:||

|ended_at|:||

|2016-08-06T14:44:03-07:00|:||

|result|:||

|ok|:||

|message|:||

|Merge Success|:||

#### _BUILD_

|started_at|:||

|2016-08-06T14:44:03-07:00|:||

|ended_at|:||

|2016-08-06T14:44:03-07:00|:||

|result|:||

|ok|:||

|command|:||

|cd /tmp/thumbs/BashoOps_prtester_105 && make build|:||

|output|:||

|BUILD OK
|:||

|exit_code|:||

|0|:||

|message|:||

|OK|:|cd /tmp/thumbs/BashoOps_prtester_105 && make build|

#### _TEST_

|started_at|:||

|2016-08-06T14:44:03-07:00|:||

|ended_at|:||

|2016-08-06T14:44:03-07:00|:||

|result|:||

|ok|:||

|command|:||

|cd /tmp/thumbs/BashoOps_prtester_105 && make test|:||

|output|:||

|TEST OK
|:||

|exit_code|:||

|0|:||

|message|:||

|OK|:|cd /tmp/thumbs/BashoOps_prtester_105 && make test|

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#105 (a5dd289244c3619a797123357e5eabdbdc3182ab on to master)
 `{:sha=>"05140b451e835a6149a9254a1b31945136c679b2", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
