### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/313: :+1: Looks good! :+1:

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:55:44.144561000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:55:47.596223000 -07:00
:result: :ok
:message: 'Merge Success: 3688e0ffb6dd13379f1e9490b57e7aa698dd8761 onto target branch:
  master'
:output: |-
  Updating db0843c..3688e0f
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:55:47.596275000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:55:47.604306000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_313 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 16:55:47.604427000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:55:47.612798000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_313 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/313_ (_3688e0ffb6dd13379f1e9490b57e7aa698dd8761_ on to _master_)

``` yaml
---
:sha: 15afbaf9e851dfeca9f90470a5817dd5b35fb709
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
