### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/407:

> Looks good! @BashoOps :simple_smile:  :+1:

### MERGE   OK

> Started at: 2016-08-08 18:50
> Duration: 3 seconds.
> Result:  OK
> Exit Code:  OK

```



Updating f031a39..f4030fc
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 18:51
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_407 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 18:51
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_407 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Code reviews from: _@davidpuddy1_, _@bobsmith1_.

##### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/407_ (_f4030fc8e2bc3793b4173cec1b101cfc900c9ffa_ on to _master_)

``` yaml
---
:sha: 55ea25b1239b3bc099c214b774fccd8094cab04e
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
