### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:

Code reviews from: @davidpuddy1, @bobsmith1.
Merging and closing this PR.
Build Status:

#### _MERGE_

``` yaml
---
- :started_at
- !ruby/object:DateTime 2016-08-06 14:51:34.748575000 -07:00

```

  #   

``` yaml
---
- :ended_at
- !ruby/object:DateTime 2016-08-06 14:51:36.674128000 -07:00

```

  #   

``` yaml
---
- :result
- :ok

```

  #   

``` yaml
---
- :message
- Merge Success

```

  #   

#### _BUILD_

``` yaml
---
- :started_at
- !ruby/object:DateTime 2016-08-06 14:51:36.674181000 -07:00

```

  #   

``` yaml
---
- :ended_at
- !ruby/object:DateTime 2016-08-06 14:51:36.682836000 -07:00

```

  #   

``` yaml
---
- :result
- :ok

```

  #   

``` yaml
---
- :command
- cd /tmp/thumbs/BashoOps_prtester_120 && make build

```

  #   

``` yaml
---
- :output
- |
  BUILD OK

```

  #   

``` yaml
---
- :exit_code
- 0

```

  #   

``` yaml
---
- :message
- - OK
  - cd /tmp/thumbs/BashoOps_prtester_120 && make build
  - |
    BUILD OK
  - 0

```

  #   

#### _TEST_

``` yaml
---
- :started_at
- !ruby/object:DateTime 2016-08-06 14:51:36.682963000 -07:00

```

  #   

``` yaml
---
- :ended_at
- !ruby/object:DateTime 2016-08-06 14:51:36.691231000 -07:00

```

  #   

``` yaml
---
- :result
- :ok

```

  #   

``` yaml
---
- :command
- cd /tmp/thumbs/BashoOps_prtester_120 && make test

```

  #   

``` yaml
---
- :output
- |
  TEST OK

```

  #   

``` yaml
---
- :exit_code
- 0

```

  #   

``` yaml
---
- :message
- - OK
  - cd /tmp/thumbs/BashoOps_prtester_120 && make test
  - |
    TEST OK
  - 0

```

  #

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#120 (618f7721e6819ac39f12879cb9638d289c2e2a44 on to master)
 `{:sha=>"34344c85acf0666e2345b41a5e925b22865505a4", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
