### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:33:45.850343000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:33:49.274124000 -07:00
:result: :ok
:message: 'Merge Success: 5a2ed26c3974c7abd7ccbe16f815a83fa5be3e2f onto target branch:
  master'
:output: |-
  Updating 0e446ce..5a2ed26
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:33:49.274195000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:33:49.283174000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_187 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:33:49.283380000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:33:49.291768000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_187 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#187 (5a2ed26c3974c7abd7ccbe16f815a83fa5be3e2f on to master)

 ```yaml ---
:sha: 190977ba4540c88116bd30ed59d5ed4596786c7f
:merged: true
:message: Pull Request successfully merged

```
```

**Pull request merged**
