### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:14:07.265167000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:14:10.075935000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:14:10.075978000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:14:10.083734000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_167 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_167 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:14:10.083879000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:14:10.092284000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_167 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_167 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#167 (c7053cb5eddbb5827b7d06327b31a15650a0f1a1 on to master)

``` ---
:sha: 37e2eec37b13e992c78488b59bcaab3933f68887
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
