### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/230: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:05:11.507232000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:05:13.958279000 -07:00
:result: :ok
:message: 'Merge Success: bc0c23824992188926e8c9d449ede65b2446558d onto target branch:
  master'
:output: |-
  Updating ce2c155..bc0c238
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:05:13.958330000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:05:13.967189000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_230 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:05:13.967345000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:05:13.975683000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_230 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#230 (bc0c23824992188926e8c9d449ede65b2446558d on to master)

``` yaml
---
:sha: 9cbf65107ae5d335a902303d6e23e12c6a427cf6
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
