### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/347:

> :+1: Looks good! :+1:

### MERGE   OK

> Started at: 2016-08-08 18:06
> Duration: 5 seconds.

```


Updating a25134e..1ae6066
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 18:06
> Duration: 0 seconds.
> 
> Exit Code: 0

```
cd /tmp/thumbs/BashoOps_prtester_347 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 18:06
> Duration: 0 seconds.
> 
> Exit Code: 0

```
cd /tmp/thumbs/BashoOps_prtester_347 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/347_ (_1ae6066fad5bf33fa6e3116f0ffff90ca33efb09_ on to _master_)

``` yaml
---
:sha: f13d225f7b81ecf0581a47192b7b1a836fe3b286
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
