### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/315: :+1: Looks good! :+1:

#### _MERGE_

```
---
:started_at: !ruby/object:DateTime 2016-08-08 16:59:08.725237000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:59:12.380070000 -07:00
:result: :ok
:message: 'Merge Success: 07040234a3affe40511186a07c0cb35b2d5455d1 onto target branch:
  master'
:output: |-
  Updating ddce99f..0704023
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

```
---
:started_at: !ruby/object:DateTime 2016-08-08 16:59:12.380134000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:59:12.388309000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_315 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

```
---
:started_at: !ruby/object:DateTime 2016-08-08 16:59:12.388450000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 16:59:12.396700000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_315 && make test
:output: |
  TEST OK
:exit_code: 0

```

| First Header | Second Header |
| --- | --- |
| Content Cell | Content Cell |
| Content Cell | Content Cell |

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/315_ (_07040234a3affe40511186a07c0cb35b2d5455d1_ on to _master_)

``` yaml
---
:sha: 71f79a4cd0ee624406f51efd6f579cc75789b091
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
