### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/397:

> :+1: Looks good! @BashoOps ;)  :+1:

### MERGE   OK

> Started at: 2016-08-08 18:43
> Duration: 3 seconds.
> Result:  OK
> Exit Code:  OK

```



Updating d6f084f..9581fe1
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 18:43
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_397 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 18:43
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_397 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/397_ (_9581fe1df991eb567c5217ec23e61cb3b0da629b_ on to _master_)

``` yaml
---
:sha: 2c4354d6a0ded73ca3361c170cc75b189733c4f8
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
