### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/351:

> :+1: Looks good! :+1:

### MERGE   OK

> Started at: 2016-08-08 18:17
> Duration: 2 seconds.
> Exit Code:  ok
> 
> ```
> **
> ```

Updating f13d225..0584dbe
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```
--------------------------------------------------


### BUILD   OK
> Started at: 2016-08-08 18:17
> Duration: 0 seconds.
> Exit Code:  0
```

_cd /tmp/thumbs/BashoOps_prtester_351 && make build_

BUILD OK

```
--------------------------------------------------


### TEST   OK
> Started at: 2016-08-08 18:17
> Duration: 0 seconds.
> Exit Code:  0
```

_cd /tmp/thumbs/BashoOps_prtester_351 && make test_

TEST OK

```
--------------------------------------------------


```

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/351_ (_0584dbec1feda3ad6eab066984ceb73e8fdfb159_ on to _master_)

``` yaml
---
:sha: e8fc89149acc338ec82722f41922f227c5ff9c9e
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
