### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:

Code reviews from: @davidpuddy1, @bobsmith1.
Merging and closing this PR.
Build Status:

#### _MERGE_

`````` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 14:58:10.282702000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 14:58:13.420488000 -07:00
:result: :ok
:message: Merge Success



#### *BUILD*

```yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 14:58:13.420531000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 14:58:13.428307000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_133 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_133 && make build
- |
  BUILD OK
- 0



#### *TEST*

```yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 14:58:13.428414000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 14:58:13.436106000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_133 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_133 && make test
- |
  TEST OK
- 0



``````

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#133 (9c69c9507b7c8c95614f2f8b1e97aeff6f96b9d5 on to master)
 `{:sha=>"1b6acce376a1885eed84b31404bac4a022858223", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
