### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:27:21.227836000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:27:23.531012000 -07:00
:result: :ok
:message: Merge Success afb320ebb54f5ffa008f3c0fc6e68d83babab05c onto master

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:27:23.531068000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:27:23.538817000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_177 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:27:23.538988000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:27:23.547413000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_177 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#177 (afb320ebb54f5ffa008f3c0fc6e68d83babab05c on to master)

``` ---
:sha: fc9586ffeb9fcc1db9566218c3975d6aa5676aa6
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
