### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/239: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 10:15:32.595784000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 10:15:35.771510000 -07:00
:result: :ok
:message: 'Merge Success: 8ade018528e2b14eef62980807777c867f54178e onto target branch:
  master'
:output: |-
  Updating 7f9e5b3..8ade018
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 10:15:35.771551000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 10:15:35.779281000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_239 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 10:15:35.779384000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 10:15:35.787191000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_239 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/239_ (_8ade018528e2b14eef62980807777c867f54178e_ on to _master_)

``` yaml
---
:sha: bd63d1b2f633423f3e4cde081a64962e0400498e
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
