### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/341: :+1: Looks good! :+1:

### MERGE   OK

Started at: 2016-08-08T17:50:24-07:00
Ended at:2016-08-08T17:50:28-07:00
Exit Code: 

---

```


Updating 2ee4cd4..266eb5f
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

### BUILD   OK

Started at: 2016-08-08T17:50:28-07:00
Ended at:2016-08-08T17:50:28-07:00
Exit Code: 0

---

```
cd /tmp/thumbs/BashoOps_prtester_341 && make build

BUILD OK


```

### TEST   OK

Started at: 2016-08-08T17:50:28-07:00
Ended at:2016-08-08T17:50:28-07:00
Exit Code: 0

---

```
cd /tmp/thumbs/BashoOps_prtester_341 && make test

TEST OK


```

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/341_ (_266eb5fe50ac94b4cb19a4cfe6d07a19a11336ed_ on to _master_)

``` yaml
---
:sha: da6aaef07ff2ae088afa1b88aba2fea766e23e57
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
