### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/354:

> :+1: Looks good! @BashoOps ;)  :+1:

### MERGE   OK

> Started at: 2016-08-08 18:24
> Duration: 4 seconds.
> Result:  OK
> Exit Code:  OK

```



Updating 044855c..8f92d42
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 18:24
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_354 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 18:24
> Duration: 0 seconds.
> Result:  OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_354 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/354_ (_8f92d42cededdfe6fe9b37a6a59132182014261b_ on to _master_)

``` yaml
---
:sha: 656edc697be168a27f6c5a99edc11a8087c7312f
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
