### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:50:58.899086000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:51:02.167112000 -07:00
:result: :ok
:message: 'Merge Success: dea0bd1499b1018a9b24eb97db4032d374f2eea4 onto target branch:
  master'
:output: |-
  Updating 155891d..dea0bd1
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:51:02.167173000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:51:02.175970000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_211 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 17:51:02.176144000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 17:51:02.184702000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_211 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#211 (dea0bd1499b1018a9b24eb97db4032d374f2eea4 on to master)

``` yaml
---
:sha: cb426d90be1f78bc9dce97fd4b24986cfff4d888
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
