### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:13:07.524315000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:13:10.708693000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:13:10.708737000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:13:10.716605000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_164 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_164 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:13:10.716731000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:13:10.724189000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_164 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_164 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#164 (5c81d731e75124fd4392b3e6f74a939d0f78637f on to master)

``` ---
:sha: a082b5d2993f484c842704e4bbb266bc08d8a5c7
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
