### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:01:49.688792000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:01:52.186117000 -07:00
:result: :ok
:message: 'Merge Success: 013bafff87c9d6ab292be2aa5e24947fb8888f58 onto target branch:
  master'
:output: |-
  Updating bac263b..013baff
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:01:52.186180000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:01:52.194281000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_228 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:01:52.194418000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:01:52.202776000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_228 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#228 (013bafff87c9d6ab292be2aa5e24947fb8888f58 on to master)

``` yaml
---
:sha: ce2c15538ba8726819daa9ba6f9c6f668d424b25
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
