### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/352:

> :+1: Looks good! :+1:

### MERGE   OK

> Started at: 2016-08-08 18:19
> Duration: 3 seconds.
> Exit Code:  ok

```


Updating e8fc891..81291e0
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 18:19
> Duration: 0 seconds.
> Exit Code:  0

```
cd /tmp/thumbs/BashoOps_prtester_352 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 18:19
> Duration: 0 seconds.
> Exit Code:  0

```
cd /tmp/thumbs/BashoOps_prtester_352 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/352_ (_81291e0b535ccad605787c6f2ddc613e1002ca2f_ on to _master_)

``` yaml
---
:sha: 338f0314836d561b1c155877528ee2eb0189da9b
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
