### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:05:58.849615000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:06:02.068277000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:06:02.068330000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:06:02.076456000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_150 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_150 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:06:02.076609000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:06:02.085548000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_150 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_150 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#150 (c57b5d0fd8a47062d7bc5ee304e19c924838b302 on to master)

  ``` --- -2662157702161547242
...

```
```

**Pull request merged**
