### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:32:45.530737000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:32:47.774887000 -07:00
:result: :ok
:message: 'Merge Success: 7cbc263ef23cda33e974de69731de7cfc92b365a onto target branch:
  master'
:output: |-
  Updating 32a1138..7cbc263
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:32:47.774939000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:32:47.782747000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_184 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:32:47.782892000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:32:47.791408000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_184 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#184 (7cbc263ef23cda33e974de69731de7cfc92b365a on to master)

 ```yaml ---
:sha: 0e446cefa079607f06fd9a520e8b3516f76d1a51
:merged: true
:message: Pull Request successfully merged

```
```

**Pull request merged**
