### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:03:06.753206000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:03:10.084552000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:03:10.084600000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:03:10.093274000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_145 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_145 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:03:10.093403000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:03:10.101309000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_145 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_145 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#145 (9f5bd3b6277341c5b27604ec7e6d5733f4b4ffd7 on to master)

 ``` --- !ruby/object:Sawyer::Resource
attrs:
  :sha: a915f4682b4e9d1cf2e44fbc393d9a9b43378968
  :merged: true
  :message: Pull Request successfully merged
_fields: !ruby/object:Set
  hash:
    :sha: true
    :merged: true
    :message: true
_rels: !ruby/object:Sawyer::Relation::Map
  map: {}

```
```

**Pull request merged**
