### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
Code reviews from: @davidpuddy1@bobsmith1
Merging and closing this PR.
Build Status:

#### _MERGE_

|started_at|:||

|2016-08-06T14:39:33-07:00|:||

|ended_at|:||

|2016-08-06T14:39:35-07:00|:||

|result|:||

|ok|:||

|message|:||

|Merge Success|:||

#### _BUILD_

|started_at|:||

|2016-08-06T14:39:35-07:00|:||

|ended_at|:||

|2016-08-06T14:39:35-07:00|:||

|result|:||

|ok|:||

|command|:||

|cd /tmp/thumbs/BashoOps_prtester_100 && make build|:||

|output|:||

|BUILD OK
|:||

|exit_code|:||

|0|:||

|message|:||

|OK|:|cd /tmp/thumbs/BashoOps_prtester_100 && make build|

#### _TEST_

|started_at|:||

|2016-08-06T14:39:35-07:00|:||

|ended_at|:||

|2016-08-06T14:39:35-07:00|:||

|result|:||

|ok|:||

|command|:||

|cd /tmp/thumbs/BashoOps_prtester_100 && make test|:||

|output|:||

|TEST OK
|:||

|exit_code|:||

|0|:||

|message|:||

|OK|:|cd /tmp/thumbs/BashoOps_prtester_100 && make test|

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#100 (9cda85f26f50a004be4737fda11d207fe2591d08 on to master) #Sawyer::Resource:0x007fb9ec02e5b0

**Pull request merged**
