### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:23:33.761386000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:23:35.933494000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:23:35.933538000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:23:35.942139000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_169 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:23:35.942271000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:23:35.950413000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_169 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#169 (93c40c018d5dd98b2bc77e42d2208a2f4dc4d629 on to master)

``` ---
:sha: 29cbcbbb27ee038f59ea98f0a9f92cd3a4fedbf7
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
