### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Build Status: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

`````` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 14:59:25.088460000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 14:59:27.254653000 -07:00
:result: :ok
:message: Merge Success



#### *BUILD*

```yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 14:59:27.254709000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 14:59:27.263111000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_136 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_136 && make build
- |
  BUILD OK
- 0



#### *TEST*

```yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 14:59:27.263239000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 14:59:27.271433000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_136 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_136 && make test
- |
  TEST OK
- 0



``````

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#136 (661e1b43c16ebc31dfdbd77f91c32a4ab45424ef on to master)
 `{:sha=>"23513d4e224e112d667dbcda33f9a76ffd60f2cd", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
