### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/320: :+1: Looks good! :+1:

`````` markdown
| *MERGE*  |   |
| | Started at |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | ```shell ``` |
``````

`````` markdown
| *BUILD*  |   |
| | Started at |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | ```shell ``` |
``````

`````` markdown
| *TEST*  |   |
| | Started at |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | ```shell ``` |
``````

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/320_ (_dc0f0218417387670b8e94a69461b492227d542f_ on to _master_)

``` yaml
---
:sha: b75dabdcdea36a86e4dda3a86002b31c47edf883
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
