### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:04:07.602713000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:04:09.866756000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:04:09.866808000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:04:09.874507000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_148 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_148 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:04:09.874629000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:04:09.883501000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_148 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_148 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#148 (45f16ce31836f551cfe0d878d0e4b3567ce8c8a1 on to master)

 ``` --- !ruby/object:Sawyer::Resource
attrs:
  :sha: 6aa26de98f2e43ada6a732c7658fdb916ac6cacd
  :merged: true
  :message: Pull Request successfully merged
_fields: !ruby/object:Set
  hash:
    :sha: true
    :merged: true
    :message: true
_rels: !ruby/object:Sawyer::Relation::Map
  map: {}

```
```

**Pull request merged**
