### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/326: :+1: Looks good! :+1:

| _MERGE_ |  |  |
| --- | --- | --- |
|  | Started at |  |
|  |  |  |
|  |  |  |

|---|---|---|
|   |   |  |
| |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | `shell` |

| _BUILD_ |  |  |
| --- | --- | --- |
|  | Started at |  |
|  |  |  |
|  |  |  |

|---|---|---|
|   |   |  |
| |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | `shell` |

| _TEST_ |  |  |
| --- | --- | --- |
|  | Started at |  |
|  |  |  |
|  |  |  |

|---|---|---|
|   |   |  |
| |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | `shell` |

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/326_ (_8120017bf881f07a46e2f1299f173d0398e82e23_ on to _master_)

``` yaml
---
:sha: 03838f5e4ea1b2711f2c5fe0b53f72a0a80a1c39
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
