### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:12:21.511638000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:12:24.253784000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:12:24.253833000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:12:24.262155000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_163 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_163 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:12:24.262297000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:12:24.270274000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_163 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_163 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#163 (b9c776d772292a7e326ab81b7b100a406a454051 on to master)

``` ---
:sha: 6a2be7522facb6acac247e4b369e0de5e9f40a98
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
