### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:39:42.853244000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:39:45.265761000 -07:00
:result: :ok
:message: 'Merge Success: 116643d50634f9790d05b308cd4743882aab26d0 onto target branch:
  master'
:output: |-
  Updating 190977b..116643d
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:39:45.265827000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:39:45.274551000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_189 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:39:45.274672000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:39:45.282335000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_189 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#189 (116643d50634f9790d05b308cd4743882aab26d0 on to master)

``` yaml
---
:sha: 91058b24d083774540d5fede5149878164ca52ea
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
