### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:

Code reviews from: @davidpuddy1, @bobsmith1.
Merging and closing this PR.
Build Status:

#### _MERGE_

``` yaml
---
- :merge
- :started_at: !ruby/object:DateTime 2016-08-06 14:55:20.088667000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:55:23.562237000 -07:00
  :result: :ok
  :message: Merge Success

```

  #   

``` yaml
---
- :build
- :started_at: !ruby/object:DateTime 2016-08-06 14:55:23.562292000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:55:23.570845000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_128 && make build
  :output: |
    BUILD OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_128 && make build
  - |
    BUILD OK
  - 0

```

  #   

``` yaml
---
- :test
- :started_at: !ruby/object:DateTime 2016-08-06 14:55:23.571015000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:55:23.579786000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_128 && make test
  :output: |
    TEST OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_128 && make test
  - |
    TEST OK
  - 0

```

  #   

#### _BUILD_

``` yaml
---
- :merge
- :started_at: !ruby/object:DateTime 2016-08-06 14:55:20.088667000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:55:23.562237000 -07:00
  :result: :ok
  :message: Merge Success

```

  #   

``` yaml
---
- :build
- :started_at: !ruby/object:DateTime 2016-08-06 14:55:23.562292000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:55:23.570845000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_128 && make build
  :output: |
    BUILD OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_128 && make build
  - |
    BUILD OK
  - 0

```

  #   

``` yaml
---
- :test
- :started_at: !ruby/object:DateTime 2016-08-06 14:55:23.571015000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:55:23.579786000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_128 && make test
  :output: |
    TEST OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_128 && make test
  - |
    TEST OK
  - 0

```

  #   

#### _TEST_

``` yaml
---
- :merge
- :started_at: !ruby/object:DateTime 2016-08-06 14:55:20.088667000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:55:23.562237000 -07:00
  :result: :ok
  :message: Merge Success

```

  #   

``` yaml
---
- :build
- :started_at: !ruby/object:DateTime 2016-08-06 14:55:23.562292000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:55:23.570845000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_128 && make build
  :output: |
    BUILD OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_128 && make build
  - |
    BUILD OK
  - 0

```

  #   

``` yaml
---
- :test
- :started_at: !ruby/object:DateTime 2016-08-06 14:55:23.571015000 -07:00
  :ended_at: !ruby/object:DateTime 2016-08-06 14:55:23.579786000 -07:00
  :result: :ok
  :command: cd /tmp/thumbs/BashoOps_prtester_128 && make test
  :output: |
    TEST OK
  :exit_code: 0
  :message:
  - OK
  - cd /tmp/thumbs/BashoOps_prtester_128 && make test
  - |
    TEST OK
  - 0

```

  #

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#128 (fe8165cf54e284f4fe893d1c86d83ccd88f03f25 on to master)
 `{:sha=>"3afd35f14739407c55fa019fe2b9ca66727fd381", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
