### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:40:44.275277000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:40:47.491720000 -07:00
:result: :ok
:message: 'Merge Success: 9430bf4d0417cc25be0e6974cda8d0e9c256e31a onto target branch:
  master'
:output: |-
  Updating 91058b2..9430bf4
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:40:47.491785000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:40:47.500642000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_192 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:40:47.500815000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:40:47.509310000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_192 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#192 (9430bf4d0417cc25be0e6974cda8d0e9c256e31a on to master)

``` yaml
---
:sha: 37ac5886e908a7e7c23a4be8f3327ec5857efc0e
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
