### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/242: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 10:16:34.146233000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 10:16:36.287617000 -07:00
:result: :ok
:message: 'Merge Success: e389c213bcbfdbbe7b670a27f0fb43510f9a5e74 onto target branch:
  master'
:output: |-
  Updating bd63d1b..e389c21
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 10:16:36.287666000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 10:16:36.295850000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_242 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-08 10:16:36.295976000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-08 10:16:36.303927000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_242 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/242_ (_e389c213bcbfdbbe7b670a27f0fb43510f9a5e74_ on to _master_)

``` yaml
---
:sha: cee21d9281343c724e91fdcea61f7c79e974df56
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
