### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/345:

> :+1: Looks good! :+1:

### MERGE   OK

> Started at: 2016 18:03
> Duration: 5 seconds.

```


Updating 77b7e7e..dba7d77
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016 18:03
> Duration: 0 seconds.

Exit Code: 0

```
cd /tmp/thumbs/BashoOps_prtester_345 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016 18:03
> Duration: 0 seconds.

Exit Code: 0

```
cd /tmp/thumbs/BashoOps_prtester_345 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/345_ (_dba7d77ce44dede49825e233eae430df0e0aa26c_ on to _master_)

``` yaml
---
:sha: c69effe0cd104cacdd5e9104d480a2e6cdd7d1ff
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
