### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
### Build Status for BashoOps/prtester/pulls/415:

Looks good @BashoOps!  :+1:

### MERGE   OK

> Started at: 2016-08-08 18:54
> Duration: 2 seconds.
> Result:  OK
> Message: Merge Success: bf7526b19d710fa2e05b9ffb7f2d3369e0b3f5d5 onto target branch: master
> Exit Code:  OK

```



Updating de1a1a4..bf7526b
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-08 18:54
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_415 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-08 18:54
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

```

cd /tmp/thumbs/BashoOps_prtester_415 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Code reviews from: _@davidpuddy1_, _@bobsmith1_.

##### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/415_ (_bf7526b19d710fa2e05b9ffb7f2d3369e0b3f5d5_ on to _master_)

``` yaml
---
:sha: 492255c7d3a8a38d176a64fe1e89f19c824367f8
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
