### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:00:46.112606000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:00:49.094271000 -07:00
:result: :ok
:message: 'Merge Success: e4b503e1410fce18be190b0fa3fe0926fd0501c8 onto target branch:
  master'
:output: |-
  Updating a5e2d9e..e4b503e
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:00:49.094323000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:00:49.102957000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_225 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:00:49.103108000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:00:49.111658000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_225 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#225 (e4b503e1410fce18be190b0fa3fe0926fd0501c8 on to master)

``` yaml
---
:sha: bac263b561def08569464e039621299d64347a67
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
