### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Build Status: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:00:43.212708000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:00:46.666430000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:00:46.666494000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:00:46.674911000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_140 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_140 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:00:46.675034000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:00:46.682946000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_140 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_140 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#140 (e1d4de9de789b48014b4d3e39738c261797b4a94 on to master)
 `{:sha=>"fc9abb4cea355a109c4361bf4e309846d611d148", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
