### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/339: :+1: Looks good! :+1:

### MERGE   OK

|   |  Started at | 2016-08-08T17:46:13-07:00 |
|   |  Ended at | 2016-08-08T17:46:15-07:00 |
|   |  Command |  |

|   |  |  |

```
Updating 73d70f3..f3de5ba
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

### BUILD   OK

|   |  Started at | 2016-08-08T17:46:15-07:00 |
|   |  Ended at | 2016-08-08T17:46:15-07:00 |
|   |  Command | cd /tmp/thumbs/BashoOps_prtester_339 && make build |

|   |  Exit Code | 0 |

```
BUILD OK


```

### TEST   OK

|   |  Started at | 2016-08-08T17:46:15-07:00 |
|   |  Ended at | 2016-08-08T17:46:15-07:00 |
|   |  Command | cd /tmp/thumbs/BashoOps_prtester_339 && make test |

|   |  Exit Code | 0 |

```
TEST OK


```

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/339_ (_f3de5baf67155fc0dee2fdffea88851fd5ff7919_ on to _master_)

``` yaml
---
:sha: 389a412008da6a5145c33d08bdedf4470d237ba6
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
