### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/332: :+1: Looks good! :+1:

| _MERGE_ | _OK_ |  |
| --- | --- | --- |
|  | Started at | 2016-08-08T17:34:15-07:00 |
|  | Ended at | 2016-08-08T17:34:20-07:00 |
|  | Command |  |
|  | Exit Code |  |
|  | Output | `log Updating 57b15bb..38b8399 |

Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)` |
|   |   |   |

| _BUILD_ | _OK_ |  |
| --- | --- | --- |
|  | Started at | 2016-08-08T17:34:20-07:00 |
|  | Ended at | 2016-08-08T17:34:20-07:00 |
|  | Command | cd /tmp/thumbs/BashoOps_prtester_332 && make build |
|  | Exit Code | 0 |
|  | Output | `log BUILD OK |
| ` |  |  |
|  |  |  |

| _TEST_ | _OK_ |  |
| --- | --- | --- |
|  | Started at | 2016-08-08T17:34:20-07:00 |
|  | Ended at | 2016-08-08T17:34:20-07:00 |
|  | Command | cd /tmp/thumbs/BashoOps_prtester_332 && make test |
|  | Exit Code | 0 |
|  | Output | `log TEST OK |
| ` |  |  |
|  |  |  |

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/332_ (_38b8399fa202ef3113d4c7dad523a2f238c1ad94_ on to _master_)

``` yaml
---
:sha: 36d5180c6787b5861bba89c1e52c915a88397a09
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
