### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/405_ (_f68a4653bfe8ffdf8b0ce9cd0b0219fa2275a384_ on to _master_)

``` yaml
---
:sha: f031a39161c3dfc07925e6525466f39645af0417
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
