### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/344:

> :+1: Looks good! :+1:

### MERGE   OK

Started at: 2016-08-08T17:59:34-07:00
Duration: 3

```


Updating da6aaef..edaaead
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

Started at: 2016-08-08T17:59:37-07:00
Duration: 0

Exit Code: 0

```
cd /tmp/thumbs/BashoOps_prtester_344 && make build

BUILD OK


```

---

### TEST   OK

Started at: 2016-08-08T17:59:37-07:00
Duration: 0

Exit Code: 0

```
cd /tmp/thumbs/BashoOps_prtester_344 && make test

TEST OK


```

---

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/344_ (_edaaeadcce50973ef1b8aca4e1a4d2d9a72a4b0a_ on to _master_)

``` yaml
---
:sha: 77b7e7e22a33429a1cf18ceb8b86612920e28c2f
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
