### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:26:20.990055000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:26:23.674664000 -07:00
:result: :ok
:message: Merge Success 5875b16e98078daae7ed03fc7655504ccd918c78 onto master

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:26:23.674718000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:26:23.683016000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_174 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:26:23.683134000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:26:23.691372000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_174 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for BashoOps/prtester PR#174 (5875b16e98078daae7ed03fc7655504ccd918c78 on to master)

``` ---
:sha: a688defdea111b4344275cdbbaa0fe96edbbb2ba
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
