### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Build Status: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:01:41.050583000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:01:44.381978000 -07:00
:result: :ok
:message: Merge Success

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:01:44.382036000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:01:44.390586000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_143 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_143 && make build
- |
  BUILD OK
- 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 15:01:44.390755000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 15:01:44.398623000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_143 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_143 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Successfully requested merge for REPO:BashoOps/prtester PR#143 (954e422f5a874bc21a55d4b2120911cb7d5165b5 on to master)
 `{:sha=>"717edc0b7b54ff79ab5ee7162e546c1b3558c9ea", :merged=>true, :message=>"Pull Request successfully merged"}`

**Pull request merged**
