### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
Code reviews from: @davidpuddy1,@bobsmith1.
Merging and closing this PR.
Build Status:

#### merge

```
---
:started_at: !ruby/object:DateTime 2016-08-05 18:22:37.949842000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 18:22:39.616366000 -07:00
:result: :ok
:message: Merge Success

```

#### build

```
---
:started_at: !ruby/object:DateTime 2016-08-05 18:22:39.616410000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 18:22:39.626228000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_16 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_16 && make build
- |
  BUILD OK
- 0

```

#### test

```
---
:started_at: !ruby/object:DateTime 2016-08-05 18:22:39.626358000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 18:22:39.634406000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_16 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_16 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Merge successfull!

**Pull request merged**
