### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
## Thumbs Build Status for BashoOps/prtester/pulls/237: :+1: Looks good! :+1:

#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

#### _MERGE_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:07:35.865247000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:07:38.478846000 -07:00
:result: :ok
:message: 'Merge Success: ab30545d66d65a1b3d4713535c3f8fcebeac542f onto target branch:
  master'
:output: |-
  Updating a6bc564..ab30545
  Fast-forward (no commit created; -m option ignored)
   testfile1 | 2 +-
   1 file changed, 1 insertion(+), 1 deletion(-)

```

#### _BUILD_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:07:38.478890000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:07:38.486966000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_237 && make build
:output: |
  BUILD OK
:exit_code: 0

```

#### _TEST_

``` yaml
---
:started_at: !ruby/object:DateTime 2016-08-06 18:07:38.487100000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-06 18:07:38.495315000 -07:00
:result: :ok
:message: OK
:command: cd /tmp/thumbs/BashoOps_prtester_237 && make test
:output: |
  TEST OK
:exit_code: 0

```

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/237_ (_ab30545d66d65a1b3d4713535c3f8fcebeac542f_ on to _master_)

``` yaml
---
:sha: 7f9e5b3297db6c5be6f1066e316538bf9701c2dc
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
