### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
Code reviews from: @davidpuddy1,@bobsmith1.
Merging and closing this PR.
Build Status:

#### merge

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:50:17.545516000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:50:19.334381000 -07:00
:result: :ok
:message: Merge Success

```

#### build

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:50:19.334429000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:50:19.342566000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_11 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_11 && make build
- |
  BUILD OK
- 0

```

#### test

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:50:19.342706000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:50:19.351533000 -07:00
:result: :ok
:command: cd /tmp/thumbs/BashoOps_prtester_11 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/BashoOps_prtester_11 && make test
- |
  TEST OK
- 0

```

**Comment by BashoOps** [comment]
Merge successfull!

**Pull request merged**
