### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/336: :+1: Looks good! :+1:

### MERGE\*   _OK_

|---|---|---|
|   |  Started at | 2016-08-08T17:39:44-07:00 |
|   |  Ended at | 2016-08-08T17:39:47-07:00 |

##### Output

`ruby Updating d234f48..862e94b
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)`

### BUILD\*   _OK_

|---|---|---|
|   |  Started at | 2016-08-08T17:39:47-07:00 |
|   |  Ended at | 2016-08-08T17:39:47-07:00 |

|   |  Command | cd /tmp/thumbs/BashoOps_prtester_336 && make build |

|   |  Exit Code | 0 |

##### Output

```ruby BUILD OK

``````


### TEST*   *OK*
|---|---|---|
|   |  Started at | 2016-08-08T17:39:47-07:00 |
|   |  Ended at | 2016-08-08T17:39:47-07:00 |

|   |  Command | cd /tmp/thumbs/BashoOps_prtester_336 && make test |


|   |  Exit Code | 0 |

##### Output
```ruby TEST OK
``````

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/336_ (_862e94bfc8aab50e053b39301436836279cad552_ on to _master_)

``` yaml
---
:sha: 73d70f372907977bd2b6009dc5bb4016b8c338a4
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
