### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
## Build Status for BashoOps/prtester/pulls/319: :+1: Looks good! :+1:

| _MERGE_  |   |
| | Started at |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | `shell` |

| _BUILD_  |   |
| | Started at |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | `shell` |

| _TEST_  |   |
| | Started at |  |
| | Started at |  |
| | Result |  |
| | Message |  |
| | Command |  |
| | Exit Code |  |
| | Output | `shell` |

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
#### Code reviews from: @davidpuddy1, @bobsmith1.

#### Merging and closing this PR.

**Comment by BashoOps** [comment]
Successfully merged _BashoOps/prtester/pulls/319_ (_7dd96437e082e6f9ab1a4fed8e777d8f4518c8be_ on to _master_)

``` yaml
---
:sha: 9312541a039bfe5c8e7ea10f42aa214a28dc7d3c
:merged: true
:message: Pull Request successfully merged

```

**Pull request merged**
